/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as InvitationsLayoutRouteImport } from './routes/invitations/_layout'
import { Route as CreateOrganizationLayoutRouteImport } from './routes/create-organization/_layout'
import { Route as errorErrorRouteImport } from './routes/(error)/error'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as OrganizationSlugLayoutRouteImport } from './routes/$organizationSlug/_layout'
import { Route as InvitationsLayoutIndexRouteImport } from './routes/invitations/_layout.index'
import { Route as CreateOrganizationLayoutIndexRouteImport } from './routes/create-organization/_layout.index'
import { Route as OrganizationSlugLayoutIndexRouteImport } from './routes/$organizationSlug/_layout.index'
import { Route as authLayoutSignUpRouteImport } from './routes/(auth)/_layout.sign-up'
import { Route as authLayoutResetPasswordRouteImport } from './routes/(auth)/_layout.reset-password'
import { Route as authLayoutLoginRouteImport } from './routes/(auth)/_layout.login'
import { Route as authLayoutForgotPasswordRouteImport } from './routes/(auth)/_layout.forgot-password'
import { Route as OrganizationSlugLayoutSettingsRouteImport } from './routes/$organizationSlug/_layout.settings'
import { Route as OrganizationSlugLayoutIntegrationsRouteImport } from './routes/$organizationSlug/_layout.integrations'
import { Route as OrganizationSlugLayoutBillingRouteImport } from './routes/$organizationSlug/_layout.billing'
import { Route as OrganizationSlugLayoutUsersIndexRouteImport } from './routes/$organizationSlug/_layout.users/index'
import { Route as OrganizationSlugLayoutTeamsIndexRouteImport } from './routes/$organizationSlug/_layout.teams/index'
import { Route as OrganizationSlugLayoutStatusUpdatesIndexRouteImport } from './routes/$organizationSlug/_layout.status-updates/index'
import { Route as OrganizationSlugLayoutAutomationsIndexRouteImport } from './routes/$organizationSlug/_layout.automations/index'
import { Route as OrganizationSlugLayoutUsersUserIdRouteImport } from './routes/$organizationSlug/_layout.users/$userId'
import { Route as OrganizationSlugLayoutTeamsTeamIdRouteImport } from './routes/$organizationSlug/_layout.teams/$teamId'
import { Route as OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRouteImport } from './routes/$organizationSlug/_layout.status-updates/$statusUpdateId'
import { Route as OrganizationSlugLayoutAutomationsScheduleIdRouteImport } from './routes/$organizationSlug/_layout.automations/$scheduleId'

const InvitationsRouteImport = createFileRoute('/invitations')()
const CreateOrganizationRouteImport = createFileRoute('/create-organization')()
const authRouteImport = createFileRoute('/(auth)')()
const OrganizationSlugRouteImport = createFileRoute('/$organizationSlug')()

const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const authRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugRoute = OrganizationSlugRouteImport.update({
  id: '/$organizationSlug',
  path: '/$organizationSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const InvitationsLayoutRoute = InvitationsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => InvitationsRoute,
} as any)
const CreateOrganizationLayoutRoute =
  CreateOrganizationLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => CreateOrganizationRoute,
  } as any)
const errorErrorRoute = errorErrorRouteImport.update({
  id: '/(error)/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => authRoute,
} as any)
const OrganizationSlugLayoutRoute = OrganizationSlugLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => OrganizationSlugRoute,
} as any)
const InvitationsLayoutIndexRoute = InvitationsLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvitationsLayoutRoute,
} as any)
const CreateOrganizationLayoutIndexRoute =
  CreateOrganizationLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CreateOrganizationLayoutRoute,
  } as any)
const OrganizationSlugLayoutIndexRoute =
  OrganizationSlugLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const authLayoutSignUpRoute = authLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutResetPasswordRoute = authLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutLoginRoute = authLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutForgotPasswordRoute =
  authLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authLayoutRoute,
  } as any)
const OrganizationSlugLayoutSettingsRoute =
  OrganizationSlugLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutIntegrationsRoute =
  OrganizationSlugLayoutIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutBillingRoute =
  OrganizationSlugLayoutBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutUsersIndexRoute =
  OrganizationSlugLayoutUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutTeamsIndexRoute =
  OrganizationSlugLayoutTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutStatusUpdatesIndexRoute =
  OrganizationSlugLayoutStatusUpdatesIndexRouteImport.update({
    id: '/status-updates/',
    path: '/status-updates/',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutAutomationsIndexRoute =
  OrganizationSlugLayoutAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutUsersUserIdRoute =
  OrganizationSlugLayoutUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutTeamsTeamIdRoute =
  OrganizationSlugLayoutTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRoute =
  OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRouteImport.update({
    id: '/status-updates/$statusUpdateId',
    path: '/status-updates/$statusUpdateId',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)
const OrganizationSlugLayoutAutomationsScheduleIdRoute =
  OrganizationSlugLayoutAutomationsScheduleIdRouteImport.update({
    id: '/automations/$scheduleId',
    path: '/automations/$scheduleId',
    getParentRoute: () => OrganizationSlugLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$organizationSlug': typeof OrganizationSlugLayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/error': typeof errorErrorRoute
  '/create-organization': typeof CreateOrganizationLayoutRouteWithChildren
  '/invitations': typeof InvitationsLayoutRouteWithChildren
  '/$organizationSlug/billing': typeof OrganizationSlugLayoutBillingRoute
  '/$organizationSlug/integrations': typeof OrganizationSlugLayoutIntegrationsRoute
  '/$organizationSlug/settings': typeof OrganizationSlugLayoutSettingsRoute
  '/forgot-password': typeof authLayoutForgotPasswordRoute
  '/login': typeof authLayoutLoginRoute
  '/reset-password': typeof authLayoutResetPasswordRoute
  '/sign-up': typeof authLayoutSignUpRoute
  '/$organizationSlug/': typeof OrganizationSlugLayoutIndexRoute
  '/create-organization/': typeof CreateOrganizationLayoutIndexRoute
  '/invitations/': typeof InvitationsLayoutIndexRoute
  '/$organizationSlug/automations/$scheduleId': typeof OrganizationSlugLayoutAutomationsScheduleIdRoute
  '/$organizationSlug/status-updates/$statusUpdateId': typeof OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRoute
  '/$organizationSlug/teams/$teamId': typeof OrganizationSlugLayoutTeamsTeamIdRoute
  '/$organizationSlug/users/$userId': typeof OrganizationSlugLayoutUsersUserIdRoute
  '/$organizationSlug/automations': typeof OrganizationSlugLayoutAutomationsIndexRoute
  '/$organizationSlug/status-updates': typeof OrganizationSlugLayoutStatusUpdatesIndexRoute
  '/$organizationSlug/teams': typeof OrganizationSlugLayoutTeamsIndexRoute
  '/$organizationSlug/users': typeof OrganizationSlugLayoutUsersIndexRoute
}
export interface FileRoutesByTo {
  '/$organizationSlug': typeof OrganizationSlugLayoutIndexRoute
  '/': typeof LayoutIndexRoute
  '/error': typeof errorErrorRoute
  '/create-organization': typeof CreateOrganizationLayoutIndexRoute
  '/invitations': typeof InvitationsLayoutIndexRoute
  '/$organizationSlug/billing': typeof OrganizationSlugLayoutBillingRoute
  '/$organizationSlug/integrations': typeof OrganizationSlugLayoutIntegrationsRoute
  '/$organizationSlug/settings': typeof OrganizationSlugLayoutSettingsRoute
  '/forgot-password': typeof authLayoutForgotPasswordRoute
  '/login': typeof authLayoutLoginRoute
  '/reset-password': typeof authLayoutResetPasswordRoute
  '/sign-up': typeof authLayoutSignUpRoute
  '/$organizationSlug/automations/$scheduleId': typeof OrganizationSlugLayoutAutomationsScheduleIdRoute
  '/$organizationSlug/status-updates/$statusUpdateId': typeof OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRoute
  '/$organizationSlug/teams/$teamId': typeof OrganizationSlugLayoutTeamsTeamIdRoute
  '/$organizationSlug/users/$userId': typeof OrganizationSlugLayoutUsersUserIdRoute
  '/$organizationSlug/automations': typeof OrganizationSlugLayoutAutomationsIndexRoute
  '/$organizationSlug/status-updates': typeof OrganizationSlugLayoutStatusUpdatesIndexRoute
  '/$organizationSlug/teams': typeof OrganizationSlugLayoutTeamsIndexRoute
  '/$organizationSlug/users': typeof OrganizationSlugLayoutUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/$organizationSlug': typeof OrganizationSlugRouteWithChildren
  '/$organizationSlug/_layout': typeof OrganizationSlugLayoutRouteWithChildren
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(error)/error': typeof errorErrorRoute
  '/create-organization': typeof CreateOrganizationRouteWithChildren
  '/create-organization/_layout': typeof CreateOrganizationLayoutRouteWithChildren
  '/invitations': typeof InvitationsRouteWithChildren
  '/invitations/_layout': typeof InvitationsLayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/$organizationSlug/_layout/billing': typeof OrganizationSlugLayoutBillingRoute
  '/$organizationSlug/_layout/integrations': typeof OrganizationSlugLayoutIntegrationsRoute
  '/$organizationSlug/_layout/settings': typeof OrganizationSlugLayoutSettingsRoute
  '/(auth)/_layout/forgot-password': typeof authLayoutForgotPasswordRoute
  '/(auth)/_layout/login': typeof authLayoutLoginRoute
  '/(auth)/_layout/reset-password': typeof authLayoutResetPasswordRoute
  '/(auth)/_layout/sign-up': typeof authLayoutSignUpRoute
  '/$organizationSlug/_layout/': typeof OrganizationSlugLayoutIndexRoute
  '/create-organization/_layout/': typeof CreateOrganizationLayoutIndexRoute
  '/invitations/_layout/': typeof InvitationsLayoutIndexRoute
  '/$organizationSlug/_layout/automations/$scheduleId': typeof OrganizationSlugLayoutAutomationsScheduleIdRoute
  '/$organizationSlug/_layout/status-updates/$statusUpdateId': typeof OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRoute
  '/$organizationSlug/_layout/teams/$teamId': typeof OrganizationSlugLayoutTeamsTeamIdRoute
  '/$organizationSlug/_layout/users/$userId': typeof OrganizationSlugLayoutUsersUserIdRoute
  '/$organizationSlug/_layout/automations/': typeof OrganizationSlugLayoutAutomationsIndexRoute
  '/$organizationSlug/_layout/status-updates/': typeof OrganizationSlugLayoutStatusUpdatesIndexRoute
  '/$organizationSlug/_layout/teams/': typeof OrganizationSlugLayoutTeamsIndexRoute
  '/$organizationSlug/_layout/users/': typeof OrganizationSlugLayoutUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$organizationSlug'
    | '/'
    | '/error'
    | '/create-organization'
    | '/invitations'
    | '/$organizationSlug/billing'
    | '/$organizationSlug/integrations'
    | '/$organizationSlug/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/$organizationSlug/'
    | '/create-organization/'
    | '/invitations/'
    | '/$organizationSlug/automations/$scheduleId'
    | '/$organizationSlug/status-updates/$statusUpdateId'
    | '/$organizationSlug/teams/$teamId'
    | '/$organizationSlug/users/$userId'
    | '/$organizationSlug/automations'
    | '/$organizationSlug/status-updates'
    | '/$organizationSlug/teams'
    | '/$organizationSlug/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$organizationSlug'
    | '/'
    | '/error'
    | '/create-organization'
    | '/invitations'
    | '/$organizationSlug/billing'
    | '/$organizationSlug/integrations'
    | '/$organizationSlug/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/$organizationSlug/automations/$scheduleId'
    | '/$organizationSlug/status-updates/$statusUpdateId'
    | '/$organizationSlug/teams/$teamId'
    | '/$organizationSlug/users/$userId'
    | '/$organizationSlug/automations'
    | '/$organizationSlug/status-updates'
    | '/$organizationSlug/teams'
    | '/$organizationSlug/users'
  id:
    | '__root__'
    | '/_layout'
    | '/$organizationSlug'
    | '/$organizationSlug/_layout'
    | '/(auth)'
    | '/(auth)/_layout'
    | '/(error)/error'
    | '/create-organization'
    | '/create-organization/_layout'
    | '/invitations'
    | '/invitations/_layout'
    | '/_layout/'
    | '/$organizationSlug/_layout/billing'
    | '/$organizationSlug/_layout/integrations'
    | '/$organizationSlug/_layout/settings'
    | '/(auth)/_layout/forgot-password'
    | '/(auth)/_layout/login'
    | '/(auth)/_layout/reset-password'
    | '/(auth)/_layout/sign-up'
    | '/$organizationSlug/_layout/'
    | '/create-organization/_layout/'
    | '/invitations/_layout/'
    | '/$organizationSlug/_layout/automations/$scheduleId'
    | '/$organizationSlug/_layout/status-updates/$statusUpdateId'
    | '/$organizationSlug/_layout/teams/$teamId'
    | '/$organizationSlug/_layout/users/$userId'
    | '/$organizationSlug/_layout/automations/'
    | '/$organizationSlug/_layout/status-updates/'
    | '/$organizationSlug/_layout/teams/'
    | '/$organizationSlug/_layout/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  OrganizationSlugRoute: typeof OrganizationSlugRouteWithChildren
  authRoute: typeof authRouteWithChildren
  errorErrorRoute: typeof errorErrorRoute
  CreateOrganizationRoute: typeof CreateOrganizationRouteWithChildren
  InvitationsRoute: typeof InvitationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug': {
      id: '/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof OrganizationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/invitations/_layout': {
      id: '/invitations/_layout'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsLayoutRouteImport
      parentRoute: typeof InvitationsRoute
    }
    '/create-organization/_layout': {
      id: '/create-organization/_layout'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationLayoutRouteImport
      parentRoute: typeof CreateOrganizationRoute
    }
    '/(error)/error': {
      id: '/(error)/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof errorErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof authRoute
    }
    '/$organizationSlug/_layout': {
      id: '/$organizationSlug/_layout'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof OrganizationSlugLayoutRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/invitations/_layout/': {
      id: '/invitations/_layout/'
      path: '/'
      fullPath: '/invitations/'
      preLoaderRoute: typeof InvitationsLayoutIndexRouteImport
      parentRoute: typeof InvitationsLayoutRoute
    }
    '/create-organization/_layout/': {
      id: '/create-organization/_layout/'
      path: '/'
      fullPath: '/create-organization/'
      preLoaderRoute: typeof CreateOrganizationLayoutIndexRouteImport
      parentRoute: typeof CreateOrganizationLayoutRoute
    }
    '/$organizationSlug/_layout/': {
      id: '/$organizationSlug/_layout/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof OrganizationSlugLayoutIndexRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/(auth)/_layout/sign-up': {
      id: '/(auth)/_layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authLayoutSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/reset-password': {
      id: '/(auth)/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authLayoutResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/login': {
      id: '/(auth)/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLayoutLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/forgot-password': {
      id: '/(auth)/_layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authLayoutForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/$organizationSlug/_layout/settings': {
      id: '/$organizationSlug/_layout/settings'
      path: '/settings'
      fullPath: '/$organizationSlug/settings'
      preLoaderRoute: typeof OrganizationSlugLayoutSettingsRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/integrations': {
      id: '/$organizationSlug/_layout/integrations'
      path: '/integrations'
      fullPath: '/$organizationSlug/integrations'
      preLoaderRoute: typeof OrganizationSlugLayoutIntegrationsRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/billing': {
      id: '/$organizationSlug/_layout/billing'
      path: '/billing'
      fullPath: '/$organizationSlug/billing'
      preLoaderRoute: typeof OrganizationSlugLayoutBillingRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/users/': {
      id: '/$organizationSlug/_layout/users/'
      path: '/users'
      fullPath: '/$organizationSlug/users'
      preLoaderRoute: typeof OrganizationSlugLayoutUsersIndexRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/teams/': {
      id: '/$organizationSlug/_layout/teams/'
      path: '/teams'
      fullPath: '/$organizationSlug/teams'
      preLoaderRoute: typeof OrganizationSlugLayoutTeamsIndexRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/status-updates/': {
      id: '/$organizationSlug/_layout/status-updates/'
      path: '/status-updates'
      fullPath: '/$organizationSlug/status-updates'
      preLoaderRoute: typeof OrganizationSlugLayoutStatusUpdatesIndexRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/automations/': {
      id: '/$organizationSlug/_layout/automations/'
      path: '/automations'
      fullPath: '/$organizationSlug/automations'
      preLoaderRoute: typeof OrganizationSlugLayoutAutomationsIndexRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/users/$userId': {
      id: '/$organizationSlug/_layout/users/$userId'
      path: '/users/$userId'
      fullPath: '/$organizationSlug/users/$userId'
      preLoaderRoute: typeof OrganizationSlugLayoutUsersUserIdRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/teams/$teamId': {
      id: '/$organizationSlug/_layout/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/$organizationSlug/teams/$teamId'
      preLoaderRoute: typeof OrganizationSlugLayoutTeamsTeamIdRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/status-updates/$statusUpdateId': {
      id: '/$organizationSlug/_layout/status-updates/$statusUpdateId'
      path: '/status-updates/$statusUpdateId'
      fullPath: '/$organizationSlug/status-updates/$statusUpdateId'
      preLoaderRoute: typeof OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
    '/$organizationSlug/_layout/automations/$scheduleId': {
      id: '/$organizationSlug/_layout/automations/$scheduleId'
      path: '/automations/$scheduleId'
      fullPath: '/$organizationSlug/automations/$scheduleId'
      preLoaderRoute: typeof OrganizationSlugLayoutAutomationsScheduleIdRouteImport
      parentRoute: typeof OrganizationSlugLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface OrganizationSlugLayoutRouteChildren {
  OrganizationSlugLayoutBillingRoute: typeof OrganizationSlugLayoutBillingRoute
  OrganizationSlugLayoutIntegrationsRoute: typeof OrganizationSlugLayoutIntegrationsRoute
  OrganizationSlugLayoutSettingsRoute: typeof OrganizationSlugLayoutSettingsRoute
  OrganizationSlugLayoutIndexRoute: typeof OrganizationSlugLayoutIndexRoute
  OrganizationSlugLayoutAutomationsScheduleIdRoute: typeof OrganizationSlugLayoutAutomationsScheduleIdRoute
  OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRoute: typeof OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRoute
  OrganizationSlugLayoutTeamsTeamIdRoute: typeof OrganizationSlugLayoutTeamsTeamIdRoute
  OrganizationSlugLayoutUsersUserIdRoute: typeof OrganizationSlugLayoutUsersUserIdRoute
  OrganizationSlugLayoutAutomationsIndexRoute: typeof OrganizationSlugLayoutAutomationsIndexRoute
  OrganizationSlugLayoutStatusUpdatesIndexRoute: typeof OrganizationSlugLayoutStatusUpdatesIndexRoute
  OrganizationSlugLayoutTeamsIndexRoute: typeof OrganizationSlugLayoutTeamsIndexRoute
  OrganizationSlugLayoutUsersIndexRoute: typeof OrganizationSlugLayoutUsersIndexRoute
}

const OrganizationSlugLayoutRouteChildren: OrganizationSlugLayoutRouteChildren =
  {
    OrganizationSlugLayoutBillingRoute: OrganizationSlugLayoutBillingRoute,
    OrganizationSlugLayoutIntegrationsRoute:
      OrganizationSlugLayoutIntegrationsRoute,
    OrganizationSlugLayoutSettingsRoute: OrganizationSlugLayoutSettingsRoute,
    OrganizationSlugLayoutIndexRoute: OrganizationSlugLayoutIndexRoute,
    OrganizationSlugLayoutAutomationsScheduleIdRoute:
      OrganizationSlugLayoutAutomationsScheduleIdRoute,
    OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRoute:
      OrganizationSlugLayoutStatusUpdatesStatusUpdateIdRoute,
    OrganizationSlugLayoutTeamsTeamIdRoute:
      OrganizationSlugLayoutTeamsTeamIdRoute,
    OrganizationSlugLayoutUsersUserIdRoute:
      OrganizationSlugLayoutUsersUserIdRoute,
    OrganizationSlugLayoutAutomationsIndexRoute:
      OrganizationSlugLayoutAutomationsIndexRoute,
    OrganizationSlugLayoutStatusUpdatesIndexRoute:
      OrganizationSlugLayoutStatusUpdatesIndexRoute,
    OrganizationSlugLayoutTeamsIndexRoute:
      OrganizationSlugLayoutTeamsIndexRoute,
    OrganizationSlugLayoutUsersIndexRoute:
      OrganizationSlugLayoutUsersIndexRoute,
  }

const OrganizationSlugLayoutRouteWithChildren =
  OrganizationSlugLayoutRoute._addFileChildren(
    OrganizationSlugLayoutRouteChildren,
  )

interface OrganizationSlugRouteChildren {
  OrganizationSlugLayoutRoute: typeof OrganizationSlugLayoutRouteWithChildren
}

const OrganizationSlugRouteChildren: OrganizationSlugRouteChildren = {
  OrganizationSlugLayoutRoute: OrganizationSlugLayoutRouteWithChildren,
}

const OrganizationSlugRouteWithChildren =
  OrganizationSlugRoute._addFileChildren(OrganizationSlugRouteChildren)

interface authLayoutRouteChildren {
  authLayoutForgotPasswordRoute: typeof authLayoutForgotPasswordRoute
  authLayoutLoginRoute: typeof authLayoutLoginRoute
  authLayoutResetPasswordRoute: typeof authLayoutResetPasswordRoute
  authLayoutSignUpRoute: typeof authLayoutSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutForgotPasswordRoute: authLayoutForgotPasswordRoute,
  authLayoutLoginRoute: authLayoutLoginRoute,
  authLayoutResetPasswordRoute: authLayoutResetPasswordRoute,
  authLayoutSignUpRoute: authLayoutSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface authRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface CreateOrganizationLayoutRouteChildren {
  CreateOrganizationLayoutIndexRoute: typeof CreateOrganizationLayoutIndexRoute
}

const CreateOrganizationLayoutRouteChildren: CreateOrganizationLayoutRouteChildren =
  {
    CreateOrganizationLayoutIndexRoute: CreateOrganizationLayoutIndexRoute,
  }

const CreateOrganizationLayoutRouteWithChildren =
  CreateOrganizationLayoutRoute._addFileChildren(
    CreateOrganizationLayoutRouteChildren,
  )

interface CreateOrganizationRouteChildren {
  CreateOrganizationLayoutRoute: typeof CreateOrganizationLayoutRouteWithChildren
}

const CreateOrganizationRouteChildren: CreateOrganizationRouteChildren = {
  CreateOrganizationLayoutRoute: CreateOrganizationLayoutRouteWithChildren,
}

const CreateOrganizationRouteWithChildren =
  CreateOrganizationRoute._addFileChildren(CreateOrganizationRouteChildren)

interface InvitationsLayoutRouteChildren {
  InvitationsLayoutIndexRoute: typeof InvitationsLayoutIndexRoute
}

const InvitationsLayoutRouteChildren: InvitationsLayoutRouteChildren = {
  InvitationsLayoutIndexRoute: InvitationsLayoutIndexRoute,
}

const InvitationsLayoutRouteWithChildren =
  InvitationsLayoutRoute._addFileChildren(InvitationsLayoutRouteChildren)

interface InvitationsRouteChildren {
  InvitationsLayoutRoute: typeof InvitationsLayoutRouteWithChildren
}

const InvitationsRouteChildren: InvitationsRouteChildren = {
  InvitationsLayoutRoute: InvitationsLayoutRouteWithChildren,
}

const InvitationsRouteWithChildren = InvitationsRoute._addFileChildren(
  InvitationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  OrganizationSlugRoute: OrganizationSlugRouteWithChildren,
  authRoute: authRouteWithChildren,
  errorErrorRoute: errorErrorRoute,
  CreateOrganizationRoute: CreateOrganizationRouteWithChildren,
  InvitationsRoute: InvitationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
