name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.7
      - uses: actions/checkout@v4
      - name: Deploy API
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/api
          packageManager: bun
      - name: Build
        run: bun install && cd apps/web-app && bun run build
      - name: Deploy Web App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=asyncstatus
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/web-app
