name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.7
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install
      - name: Deploy API
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/api
          packageManager: bun
      - name: Build Web App
        run: cd apps/web-app && VITE_API_URL=${{ secrets.API_URL }} VITE_WEB_APP_URL=${{ secrets.WEB_APP_URL }} VITE_MARKETING_APP_URL=${{ secrets.MARKETING_APP_URL }} VITE_STRIPE_CUSTOMER_PORTAL=${{ secrets.STRIPE_CUSTOMER_PORTAL_URL }} bun run build
      - name: Deploy Web App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=web-app
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/web-app
