name: Deploy Backend and Web App
on:
  push:
    branches:
      - main
    paths-ignore:
      - apps/marketing-app/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install

      - name: Deploy API
        id: deploy-api
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/api
          packageManager: bun
          secrets: |
            SLACK_CLIENT_ID
            SLACK_CLIENT_SECRET
            SLACK_SIGNING_SECRET
            SLACK_BOT_TOKEN
        env:
            SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
            SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
            SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Build Web App
        run: cd apps/web-app && bun run build
        env:
          VITE_API_URL: ${{ vars.PUBLIC_API_URL }}
          VITE_WEB_APP_URL: ${{ vars.WEB_APP_URL }}
          VITE_MARKETING_APP_URL: ${{ vars.MARKETING_APP_URL }}
          VITE_STRIPE_CUSTOMER_PORTAL: ${{ vars.VITE_STRIPE_CUSTOMER_PORTAL }}

      - name: Deploy Web App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=web-app
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/web-app