name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.7
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install

      - name: Deploy API
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/api
          packageManager: bun

      - name: Build Web App
        run: cd apps/web-app && bun run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_WEB_APP_URL: ${{ secrets.VITE_WEB_APP_URL }}
          VITE_MARKETING_APP_URL: ${{ secrets.VITE_MARKETING_APP_URL }}
          VITE_STRIPE_CUSTOMER_PORTAL: ${{ secrets.VITE_STRIPE_CUSTOMER_PORTAL }}

      - name: Deploy Web App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=web-app
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/web-app

      - name: Build Marketing App
        run: cd apps/marketing-app && bun run build
        env:
          NEXT_PUBLIC_STRIPE_LINK: ${{ vars.NEXT_PUBLIC_STRIPE_LINK }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ vars.NEXT_PUBLIC_POSTHOG_HOST }}
          NEXT_PUBLIC_GAID: ${{ vars.NEXT_PUBLIC_GAID }}
          NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

      - name: Deploy Marketing App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=marketing-app
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/marketing-app
