name: Deploy Backend and Web App
on:
  push:
    branches:
      - main
    paths-ignore:
      - apps/marketing-app/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install
      # disabling biome because we need to cleanup the codebase first
      # - name: Setup Biome
      #   uses: biomejs/setup-biome@v2
      #   with:
      #     version: latest
      # - name: Run Biome
      #   run: biome ci .

      - name: Deploy API
        id: deploy-api
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/api
          packageManager: bun

      - name: Build Web App
        run: cd apps/web-app && bun run build
        env:
          VITE_API_URL: ${{ vars.PUBLIC_API_URL }}
          VITE_WEB_APP_URL: ${{ vars.WEB_APP_URL }}
          VITE_MARKETING_APP_URL: ${{ vars.MARKETING_APP_URL }}
          VITE_STRIPE_CUSTOMER_PORTAL: ${{ vars.VITE_STRIPE_CUSTOMER_PORTAL }}

      - name: Deploy Web App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=web-app
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/web-app
