name: Deploy Marketing App
on:
  push:
    branches:
      - main
    paths-ignore:
      - apps/api/**
      - apps/web-app/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install

      - name: Build And Deploy Marketing App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: bun run deploy
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/marketing-app
          secrets: |
            NEXT_PUBLIC_STRIPE_LINK
            NEXT_PUBLIC_POSTHOG_KEY
            NEXT_PUBLIC_POSTHOG_HOST
            NEXT_PUBLIC_GAID
            NEXT_PUBLIC_APP_URL
            NEXT_PUBLIC_API_URL
        env:
          NEXT_PUBLIC_STRIPE_LINK: ${{ vars.NEXT_PUBLIC_STRIPE_LINK }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ vars.NEXT_PUBLIC_POSTHOG_HOST }}
          NEXT_PUBLIC_GAID: ${{ vars.NEXT_PUBLIC_GAID }}
          NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
